spring:
  jpa:
#    database: MARIADB
    show-sql: false
    hibernate:
      dll: true
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://databased.cqpwzda9ijyr.us-east-2.rds.amazonaws.com:3306/A
    username: admin
    password: hesellsseashells1!
    autoReconnect: true
    maxActive: 500

  logging:
    level: DEBUG

  server:
    session:
    sessionTimeout: 60
    cookie:
      max-age: 36000
      timeout: 36000